# Generated by Django 4.2.10 on 2024-07-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='managment/pano_image')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pano_image', to='management.patient')),
            ],
        ),
    ]
