# Generated by Django 4.2.10 on 2024-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_doctor_user_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramaimage',
            name='image',
            field=models.ImageField(upload_to='managment'),
        ),
    ]
