# Generated by Django 4.2.10 on 2024-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_panoramaimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='period',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='specialize',
            field=models.CharField(choices=[('GENERAL', 'General'), ('COSMETIC', 'Cosmetic'), ('PEDIATRIC', 'Pediatric'), ('ORALSERGURY', 'Oral Surgery'), ('ORTHODONTICS', 'Orthodontics')], default=22, max_length=255),
            preserve_default=False,
        ),
    ]
