# Generated by Django 4.2.10 on 2024-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_reservation_period_reservation_specialize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
