# Generated by Django 4.2.10 on 2024-08-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='specialize',
        ),
    ]
