# Generated by Django 4.2.10 on 2024-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_reservation_specialize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('8:00 AM', '8:00 AM'), ('9:00 AM', '9:00 AMc'), ('10:00 AM', '10:00 AM'), ('5:00 PM', '5:00 PM'), ('6:00 PM', '6:00 PM'), ('7:00 PM', '7:00 PM')], default=10, max_length=255),
            preserve_default=False,
        ),
    ]
