# Generated by Django 4.2.10 on 2024-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramaimage',
            name='image_with_contours',
            field=models.ImageField(blank=True, null=True, upload_to='segmentation'),
        ),
        migrations.AddField(
            model_name='panoramaimage',
            name='segmentation_colored_result_with_contours',
            field=models.ImageField(blank=True, null=True, upload_to='segmentation'),
        ),
        migrations.AddField(
            model_name='panoramaimage',
            name='segmentation_result',
            field=models.ImageField(blank=True, null=True, upload_to='segmentation'),
        ),
    ]
