# Generated by Django 4.2.10 on 2024-08-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_panoramaimage_image_with_contours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caries', models.ImageField(upload_to='analysis')),
                ('image_analysis', models.TextField(blank=True, max_length=255, null=True)),
                ('restorations', models.ImageField(upload_to='analysis')),
                ('teeth_bunds', models.TextField(blank=True, max_length=255, null=True)),
                ('teeth_section', models.ImageField(upload_to='analysis')),
                ('panorama_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_id', to='management.panoramaimage')),
            ],
        ),
    ]
