# Generated by Django 4.2.10 on 2024-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('choice', models.CharField(choices=[('1', 'Detect Caries'), ('2', 'Detect Restorations'), ('3', 'Image Analysis'), ('4', 'Dental Bunds'), ('5', 'Teeth Section with Rectangles')], max_length=100)),
            ],
        ),
    ]
