# Generated by Django 4.2.10 on 2024-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AddField(
            model_name='option',
            name='wisdom_teeth',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
