# Generated by Django 4.2.10 on 2024-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_delete_imageupload_option_wisdom_teeth'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='options',
            field=models.CharField(choices=[('CARIES', 'Caries'), ('RESTORITIONS', 'Restorations'), ('IMAGE_ANALYSIS', 'Image_Analysis'), ('TEETH_BUNDS', 'Teeth_Bunds'), ('TEETH_SECTION', 'Teeth_Section'), ('WISDOM_TEETH', 'wisdom_teeth')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
