# Generated by Django 4.2.10 on 2024-08-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_option_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='panorama_id',
        ),
        migrations.AddField(
            model_name='option',
            name='panorama',
            field=models.OneToOneField(default=252, on_delete=django.db.models.deletion.CASCADE, related_name='panorama', to='management.panoramaimage'),
            preserve_default=False,
        ),
    ]
