# Generated by Django 4.2.10 on 2024-08-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_remove_option_panorama_id_option_panorama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='panorama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_id', to='management.panoramaimage'),
        ),
    ]
