# Generated by Django 4.2.10 on 2024-08-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_option_panorama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='options',
        ),
    ]
