# Generated by Django 4.2.10 on 2024-08-21 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_option_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='wisdom_teeth',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='analysis'),
            preserve_default=False,
        ),
    ]
