# Generated by Django 4.2.10 on 2024-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_option_wisdom_teeth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='caries',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='restorations',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='teeth_section',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='wisdom_teeth',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
